CREATE TABLE dts."user" (
    id bigint generated by default as identity (maxvalue 2147483647) constraint user_pk primary key,
    username text not null constraint user_un UNIQUE,
    created_by text,
    created_at timestamp with time zone,
    updated_by text,
    updated_at timestamp with time zone,
    first_name character varying(200),
    last_name character varying(200),
    email text,
    is_internal boolean NOT NULL
);


CREATE TABLE dts.user_ldap_groups (
    user_id integer NOT NULL,
    ldap_group_id smallint NOT NULL,
    FOREIGN KEY (user_id) REFERENCES dts."user"(id)
);